# Generated by Django 4.2 on 2023-04-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("tipo_planta", models.CharField(max_length=30)),
                ("enfermedad", models.BooleanField()),
                ("descripcion_enfermedad", models.CharField(max_length=500)),
                ("imagen_dir", models.CharField(max_length=250)),
            ],
        ),
    ]
